---
sudo: false
language: ruby
cache: bundler
env:
  - "RAILS_VERSION=6.0.0"
  - "RAILS_VERSION=6.1.0"
  - "RAILS_VERSION=7.0.0"
rvm:
  - 2.6.5
  - 2.7.2
  - 3.0.0
before_install: gem update bundler
jobs:
  exclude:
  - rvm: 2.6.5
    env: "RAILS_VERSION=7.0.0"
